	Comment( WagonBrakeSystem.inc )

	
	BrakeEquipmentType							( "Distributor,auxilary_reservoir" )
	BrakeSystemType								( "Air_twin_pipe" )
		MaxBrakeForce								( 33.60kN )
	MaxReleaseRate								( 30 )
	MaxApplicationRate							( 15 )
	MaxAuxilaryChargingRate							( 20 )

	BrakeDistributorTrainPipeAuxResPressureDifferenceForApplication		( 1 )
	BrakeDistributorEmergencyApplicationPressure				( 0 )
	BrakeDistributorEmergencyApplicationRate				( 20 ) 

	BrakeCylinderPressureForMaxBrakeBrakeForce				( 51.4 )

	BrakeDistributorFullServicePressure					( 51.4 )
	BrakeDistributorMaxAuxilaryResPressure					( 73 )
	BrakeDistributorEmergencyResPressure					( 73 )
	BrakeDistributorReleaseRate						( 15 )
	BrakeDistributorApplicationRate						( 20 )
	BrakeDistributorTrainPipeControlRatio					( 2.27 )
	BrakeDistributorNormalFullReleasePressure				( 73 )


