 	Lights (	33

        comment ( ======================= Lumieres Joueur ======================= )

		Light (
			comment ( Sphere of light bright  )
			Type ( 1 )
			Conditions (
				Headlight ( 3 )
				Unit ( 2 )
			)
			Cycle ( 0 )
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( 0.83 1.67 10.077 )
					Transition ( 0 )
					Radius ( 20.0 )
					Angle ( 25.0 )
				)
			)
		)

		Light (
			comment ( Sphere of light dim  )
			Type ( 1 )
			Conditions (
				Headlight ( 2 )
				Unit ( 2 )
			)
			Cycle ( 0 )
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( 80ffffff )
					Position ( 0.83 1.67 10.077 )
					Transition ( 0 )
					Radius ( 12.0 )
					Angle ( 25.0 )
				)
			)
		)
		Light (
			comment ( Fanal Droit )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 2 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( 80ffffff )
					Position ( -0.83 1.67 10.077 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
		Light (
			comment ( Fanal Droit )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 5 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( 80ffffff )
					Position ( -0.83 1.67 10.077 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
		Light (
			comment ( Projo Droit )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 2 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( -0.83 1.67 10.077 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.6 )
				)
			)
		)
		Light (
			comment ( Projo Droit )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 5 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( -0.83 1.67 10.077 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.6 )
				)
			)
		)
		Light (
			comment ( Fanal Gauche )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 2 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( 80ffffff )
					Position ( 0.83 1.67 10.077 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
		Light (
			comment ( Fanal Gauche )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 5 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( 80ffffff )
					Position ( 0.83 1.67 10.077 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
		Light (
			comment ( Projo Gauche )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 2 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( 0.83 1.67 10.077 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.6 )
				)
			)
		)
		Light (
			comment ( Projo Gauche )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 5 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( 0.83 1.67 10.077 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.6 )
				)
			)
		)



        comment ( ======================= 3eme phare ======================= )

		Light (
			comment ( 3eme Phare Fanal )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 2 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( 80ffffff )
					Position ( 0 3.567 6.706 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
		Light (
			comment ( 3eme Phare Fanal )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 5 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( 80ffffff )
					Position ( 0 3.567 6.706 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
		Light (
			comment ( 3eme Phare Projo )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 2 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( 0 3.567 6.706 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.6 )
				)
			)
		)
		Light (
			comment ( 3eme Phare Projo )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 5 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( 0 3.567 6.706 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.6 )
				)
			)
		)

        comment ( ======================= LED Rouges ======================= )

		Light (
			comment ( Rouge Led Droit )
			Type ( 0 )
			Conditions (
				Headlight ( 0 )
				Unit ( 3 )
			)
			FadeIn ( 0 )
			FadeOut ( 0 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffff0000 )
					Position ( -0.563 1.67 10.231 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)


		Light (
			comment ( Rouge Led Droit )
			Type ( 0 )
			Conditions (
				Headlight ( 0 )
				Unit ( 4 )
			)
			FadeIn ( 0 )
			FadeOut ( 0 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffff0000 )
					Position ( -0.563 1.67 10.231 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)


		Light (
			comment ( Rouge Led Gauche )
			Type ( 0 )
			Conditions (
				Headlight ( 0 )
				Unit ( 3 )
			)
			FadeIn ( 0 )
			FadeOut ( 0 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffff0000 )
					Position ( 0.563 1.67 10.231 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)


		Light (
			comment ( Rouge Led Gauche )
			Type ( 0 )
			Conditions (
				Headlight ( 0 )
				Unit ( 4 )
			)
			FadeIn ( 0 )
			FadeOut ( 0 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffff0000 )
					Position ( 0.563 1.67 10.231 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)


        comment ( ======================= Feux trafic ======================= )

		Light (
			comment ( AV DR trafic )
			Type ( 0 )
			Conditions (
				Headlight ( 0 )
				Unit ( 2 )
				Control ( 1 )
				Service ( 2 )
				TimeOfDay ( 0 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffffffaa )
					Position ( -0.83 1.67 10.077 )
					Azimuth ( 0.0 0.0 0.0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
		Light (
			comment ( AV GA trafic )
			Type ( 0 )
			Conditions (
				Headlight ( 0 )
				Unit ( 2 )
				Control ( 1 )
				Service ( 2 )
				TimeOfDay ( 0 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffffffaa )
					Position ( 0.83 1.67 10.077 )
					Azimuth ( 0.0 0.0 0.0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
		Light (
			comment ( AV haut trafic )
			Type ( 0 )
			Conditions (
				Headlight ( 0 )
				Unit ( 2 )
				Control ( 1 )
				Service ( 2 )
				TimeOfDay ( 0 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffffffaa )
					Position ( 0 3.567 6.706 )
					Azimuth ( 0.0 0.0 0.0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
		Light (
			comment ( AR DR trafic )
			Type ( 0 )
			Conditions (
				Headlight ( 0 )
				Unit ( 3 )
				Control ( 1 )
				Service ( 2 )
				TimeOfDay ( 0 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( aaff3300 )
					Position ( -0.563 1.67 10.231 )
					Azimuth ( 0.0 0.0 0.0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
		Light (
			comment ( AR GA trafic )
			Type ( 0 )
			Conditions (
				Headlight ( 0 )
				Unit ( 3 )
				Control ( 1 )
				Service ( 2 )
				TimeOfDay ( 0 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( aaff3300 )
					Position ( 0.563 1.67 10.231 )
					Azimuth ( 0.0 0.0 0.0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)

        comment ( ======================= LED rouges maintien de service ======================= )

		Light (
			comment ( Rouge Led MTS Droit )
			Type ( 0 )
			Conditions (
				Headlight ( 1 )
				Unit ( 2 )
			)
			FadeIn ( 0 )
			FadeOut ( 0 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffff0000 )
					Position ( -0.563 1.67 10.231 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
		Light (
			comment ( Rouge Halo MTS Droit )
			Type ( 0 )
			Conditions (
				Headlight ( 1 )
				Unit ( 2 )
			)
			FadeIn ( 0 )
			FadeOut ( 0 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( 70ff0000 )
					Position ( -0.563 1.67 10.231 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)

		Light (
			comment ( Rouge Led MTS Droit )
			Type ( 0 )
			Conditions (
				Headlight ( 1 )
				Unit ( 5 )
			)
			FadeIn ( 0 )
			FadeOut ( 0 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffff0000 )
					Position ( -0.563 1.67 10.231 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
		Light (
			comment ( Rouge Halo MTS Droit )
			Type ( 0 )
			Conditions (
				Headlight ( 1 )
				Unit ( 5 )
			)
			FadeIn ( 0 )
			FadeOut ( 0 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( 70ff0000 )
					Position ( -0.563 1.67 10.231 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)

		Light (
			comment ( Rouge Led MTS Gauche )
			Type ( 0 )
			Conditions (
				Headlight ( 1 )
				Unit ( 2 )
			)
			FadeIn ( 0 )
			FadeOut ( 0 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffff0000 )
					Position ( 0.563 1.67 10.231 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
		Light (
			comment ( Rouge Halo MTS Gauche )
			Type ( 0 )
			Conditions (
				Headlight ( 1 )
				Unit ( 2 )
			)
			FadeIn ( 0 )
			FadeOut ( 0 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( 70ff0000 )
					Position ( 0.563 1.67 10.231 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)

		Light (
			comment ( Rouge Led MTS Gauche )
			Type ( 0 )
			Conditions (
				Headlight ( 1 )
				Unit ( 5 )
			)
			FadeIn ( 0 )
			FadeOut ( 0 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( ffff0000 )
					Position ( 0.563 1.67 10.231 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
		Light (
			comment ( Rouge Halo MTS Gauche )
			Type ( 0 )
			Conditions (
				Headlight ( 1 )
				Unit ( 5 )
			)
			FadeIn ( 0 )
			FadeOut ( 0 )
			Cycle ( 0 )
			States (
				1 
				State (
					Duration ( 0.0 )
					LightColour ( 70ff0000 )
					Position ( 0.563 1.67 10.231 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
	)