	Comment( Description.inc )

    Description (
	" Rame TGV Atlantique n°325.\n\n"+
	" Utilisée sur les relations Paris, façade atlantique"\n\n"+
	" Rame construite par GEC ALSTOM en 1994.\n\n"+
	" Fonctionne sous les 2 tensions Françaises 1500v continu et 25kv"+
	" Puissance: 8800kw sous 25kv et 3680 kw sous 1500v.\n\n"+
	" Vitesse maximale : 300 km/h.\n\n"+
	" Longueur de la rame : 237m.\n\n"+
	" Poids de la rame : 444 t.\n\n"+
	" Composition: 1 Motrice+ 3 voitures de 1ère+1 voiture bar + 6 voitures de 2ème"+ 
	" + 1 motrice\n\n."+
	" Les rames sont couplables seulement entre elles."

	"Locos,cars Jean-Prisca COMBAZ \n"+
	"Bogies Jean-Prisca COMBAZ \n"+
	"Passenger views Jean-Prisca COMBAZ \n"+
	"Cabview Jean-Prisca COMBAZ \n"+
	"Sounds Jean-Prisca COMBAZ and Guillaume RAUNIER \n"+
      	"Eng,Wag files Jean-Prisca COMBAZ \n"+
      	"Beta tester all the team and \n"+
      	"? \n\n"+
      	"Project Leader          Jean-Prisca COMBAZ \n\n"
    )