	Comment( EngineBrakeSystem.inc )

   	Antislip ( 1 )
	
    	comment(-------- Freinage --------)

	BrakeEquipmentType							( "Distributor,auxilary_reservoir,emergency_brake_reservoir,Handbrake" )
	BrakeSystemType								( "Air_twin_pipe" )
	MaxBrakeForce								( 69.0kN )
	MaxReleaseRate								( 40 )
	MaxApplicationRate							( 20 )
	MaxAuxilaryChargingRate							( 25 )

	BrakeDistributorTrainPipeAuxResPressureDifferenceForApplication		( 1 )
	BrakeDistributorEmergencyApplicationPressure				( 0 )
	BrakeDistributorEmergencyApplicationRate				( 20 ) 

	BrakeCylinderPressureForMaxBrakeBrakeForce				( 3.4bar )

	BrakeDistributorFullServicePressure					( 3bar )
	BrakeDistributorMaxAuxiliaryResPressure					( 5bar )
	BrakeDistributorEmergencyResPressure					( 5bar )
	BrakeDistributorReleaseRate						( 20 )
	BrakeDistributorApplicationRate						( 25 )
	BrakeDistributorTrainPipeControlRatio					( 3.27 )
	BrakeDistributorNormalFullReleasePressure				( 73 )


